### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-js-plugin#17]
1. Здесь шаг не надо делать
![magnet](https://user-images.githubusercontent.com/51824674/87550082-79f7c680-c6d0-11ea-9962-f4c972235e4c.gif)

2. Улучшить синхронизацию с панелью управления
![step](https://user-images.githubusercontent.com/51824674/87550193-98f65880-c6d0-11ea-89a2-e582fb8cb137.gif)

![synch](https://user-images.githubusercontent.com/51824674/87550196-9b58b280-c6d0-11ea-87f9-b52f9df103f7.gif)

![synch2](https://user-images.githubusercontent.com/51824674/87550201-9c89df80-c6d0-11ea-9c2b-137f4b2f240c.gif)

![undefined](https://user-images.githubusercontent.com/51824674/87550205-9dbb0c80-c6d0-11ea-8b81-fe258fadad24.gif)

**Comment by Fr0stmourne** [comment]
По первому пункту не уверен, что правильно понял, но сделал так, что шаг начинает отрисовываться при условии max - min >= 2*step

**Comment by iatsdotfatr** [comment]
1. В первом пункте имелось ввиду убрать эффект примагничивания, то есть делать либо полный шаг, либо не делать вообще. А теперь баг с шагом появился и со шкалы один пункт пропал, то есть при шаге 3 и 4 на шкале не отрисовывается 3 и 4 соответственно.
![Peek 2020-07-20 21-54](https://user-images.githubusercontent.com/51824674/87959616-fb869480-cad4-11ea-8a83-6ca18330f4c3.gif)

2. 
![Peek 2020-07-20 21-58](https://user-images.githubusercontent.com/51824674/87959675-0e996480-cad5-11ea-8120-18de212d087c.gif)

3. Progress bar тоже надо сделать, это теперь обязательное уловие.
![Screenshot from 2020-07-20 22-06-20](https://user-images.githubusercontent.com/51824674/87959881-57511d80-cad5-11ea-946f-378b9779666e.png)

**Comment by Fr0stmourne** [comment]
1. Это не баг, а как раз то, как я намеренно сделал, верну как было, а про примагничивание зачем так делать? Мне бы  как пользователю показалось, что это что-то странное и багованное, если бы я не мог достигнуть конца слайдера просто из-за того, что шаг не совпадает с остатком на шкале. Если так сделать, то в качестве максимального значения слайдера большинство значений вообще смысла не будет иметь, потому что будут работать только подходящие под текущий шаг. Из-за этого придется постоянно думать, какое выставить максимальное значение, чтобы всюду ползунком можно было добраться. В общем, я бы предпочел оставить в текущем виде, если ты не против.

**Comment by Fr0stmourne** [comment]
Всё остальное сделал, можешь смотреть
