### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-js-plugin#18]
1. Модификаторы оформи как в первом проекте.
![mods](https://user-images.githubusercontent.com/51824674/88408249-1cacf500-cdf5-11ea-9c97-6f1bdd0ee637.png)

2. Вынеси в отдельный метод
![Screenshot from 2020-07-24 21-30-02](https://user-images.githubusercontent.com/51824674/88409041-33078080-cdf6-11ea-8d70-f0d9aca0e799.png)

Просто как совет, делай вложение через амперсанд только элементов, модификаторов и псевдо(классов/элементов), если большой scss файл с большим количеством подобых вложений, неудобно делать поиск.
![advice](https://user-images.githubusercontent.com/51824674/88409362-aa3d1480-cdf6-11ea-8591-acdec8d1f1e0.png)

**Comment by Fr0stmourne** [comment]
Готово
